# Generated by Django 5.0.4 on 2026-07-23 14:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pmb_notice_id', models.CharField(max_length=50, verbose_name='ID Notice PMB')),
                ('pmb_item_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Exemplaire PMB')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Titre du document')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Auteur')),
                ('loan_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du prêt')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour prévue')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de retour effectif')),
                ('status', models.CharField(default='En cours', max_length=50, verbose_name='Statut du prêt')),
                ('is_renewable', models.BooleanField(default=False, verbose_name='Renouvelable')),
                ('is_late', models.BooleanField(default=False, verbose_name='En retard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prêt',
                'verbose_name_plural': 'Prêts',
                'ordering': ['-created_at'],
            },
        ),
    ]
