# Generated by Django 5.0.4 on 2026-07-28 11:08

import django.contrib.auth.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_source', models.CharField(choices=[('local', 'Authentification Interne Django'), ('pmb', 'Authentification SIGB PMB')], default='pmb', help_text="Origine de l'authentification (local ou pmb)", max_length=10)),
                ('pmb_lecteur_id', models.CharField(blank=True, db_index=True, help_text='ID unique de la fiche emprunteur/lecteur dans PMB', max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('BIBLIO', 'Bibliothécaire'), ('ETUDIANT', 'Étudiant en fin de cycle'), ('ENSEIGNANT', 'Enseignant / Chercheur')], db_index=True, default='ETUDIANT', max_length=15)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='Préférences utilisateur au format JSON (filtres, thèmes, etc.)')),
                ('last_pmb_sync', models.DateTimeField(blank=True, help_text='Horodatage de la dernière synchronisation réussie des données depuis PMB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du compte sur le portail')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='portal_user_set', related_query_name='portal_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='portal_user_set', related_query_name='portal_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur du Portail',
                'verbose_name_plural': 'Utilisateurs du Portail',
                'db_table': 'portal_user',
                'ordering': ['-created_at'],
            },
        ),
    ]
