# Generated by Django 5.0.4 on 2026-07-21 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='digital_documents/', verbose_name='Fichier (PDF)')),
                ('pmb_notice_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Notice PMB associée')),
                ('is_restricted', models.BooleanField(default=True, verbose_name='Réservé aux connectés ?')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Numérique',
                'verbose_name_plural': 'Documents Numériques',
                'ordering': ['-created_at'],
            },
        ),
    ]
