# Generated by Django 5.0.4 on 2026-07-23 14:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name="Lu par l'administration ?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Illustration')),
                ('category', models.CharField(choices=[('Informations', 'Informations'), ('Acquisitions', 'Acquisitions'), ('Événements', 'Événements'), ('Formation', 'Formation'), ('Annonces', 'Annonces')], default='Informations', max_length=50, verbose_name='Catégorie')),
                ('is_event', models.BooleanField(default=False, verbose_name='Est-ce un événement ?')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'événement")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('publish_until', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Actualité / Événement',
                'verbose_name_plural': 'Actualités & Événements',
                'ordering': ['-created_at'],
            },
        ),
    ]
