# Generated by Django 5.0.4 on 2026-07-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="URL de l'image externe"),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Informations', 'Informations'), ('Acquisitions', 'Acquisitions'), ('Événements', 'Événements'), ('Formation', 'Formation'), ('Annonces', 'Annonces'), ('Services', 'Services'), ('Ressources', 'Ressources')], default='Informations', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Illustration (upload local)'),
        ),
    ]
