# Generated by Django 4.2.7 on 2026-07-24 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre du mémoire')),
                ('abstract', models.TextField(verbose_name='Résumé')),
                ('department', models.CharField(max_length=150, verbose_name='Filière / Département')),
                ('graduation_year', models.IntegerField(verbose_name="Année d'obtention")),
                ('file', models.FileField(upload_to='memoires_files/', verbose_name='Fichier PDF du mémoire')),
                ('jury_document', models.FileField(blank=True, null=True, upload_to='jury_documents/', verbose_name='Document signé du jury')),
                ('physical_deposit_confirmed', models.BooleanField(default=False, verbose_name='Dépôt physique confirmé')),
                ('status', models.CharField(choices=[('incomplet', 'Incomplet'), ('en_attente', 'En attente de validation'), ('valide', 'Validé'), ('quitus_genere', 'Quitus généré'), ('quitus_signe', 'Quitus signé'), ('rejete', 'Rejeté')], default='incomplet', max_length=20, verbose_name='Statut')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Motif de rejet')),
                ('quitus_file', models.FileField(blank=True, null=True, upload_to='quitus_files/', verbose_name='Fichier PDF du Quitus')),
                ('is_quitus_signed', models.BooleanField(default=False, verbose_name='Quitus signé')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('quitus_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération du quitus')),
                ('quitus_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature du quitus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Mémoire',
                'verbose_name_plural': 'Mémoires',
                'ordering': ['-created_at'],
            },
        ),
    ]
