# Generated by Django 5.0.4 on 2026-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='is_quitus_physically_signed',
            field=models.BooleanField(default=False, verbose_name='Quitus signé physiquement'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='quitus_physically_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature physique'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='is_quitus_signed',
            field=models.BooleanField(default=False, verbose_name='Quitus signé électroniquement'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='quitus_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature électronique'),
        ),
    ]
