# Generated by Django 5.0.4 on 2026-07-28 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0002_memoire_is_quitus_physically_signed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoire',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dépôt', 'verbose_name_plural': 'Dépôts'},
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='department',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='file',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='jury_document',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='quitus_generated_at',
        ),
        migrations.RemoveField(
            model_name='memoire',
            name='validated_at',
        ),
        migrations.AddField(
            model_name='memoire',
            name='convocation_sent',
            field=models.BooleanField(default=False, verbose_name='Convocation envoyée'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='convocation_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de la convocation"),
        ),
        migrations.AddField(
            model_name='memoire',
            name='documents_conform',
            field=models.BooleanField(default=False, verbose_name='Documents conformes'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='examinateur_1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Examinateur 1'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='examinateur_2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Examinateur 2'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='examinateur_3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Examinateur 3'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='filiere',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filière / Département'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom complet'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='laboratoire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Laboratoire / Spécialité'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='librarian_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes du bibliothécaire'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='matricule',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='memoires_pdf/', verbose_name='Fichier PDF'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='physical_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de vérification physique'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='president_jury',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Président du jury'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='quitus_available_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de disponibilité du quitus'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='quitus_retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de retrait du quitus'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='relance_sent',
            field=models.BooleanField(default=False, verbose_name='Relance envoyée'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='relance_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi de la relance"),
        ),
        migrations.AddField(
            model_name='memoire',
            name='scanned_document',
            field=models.FileField(blank=True, null=True, upload_to='memoires_scanned/', verbose_name='Document scanné signé'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='type_document',
            field=models.CharField(choices=[('MEMOIRE', 'Mémoire de Master'), ('THESE', 'Thèse de Doctorat')], default='MEMOIRE', max_length=10, verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='unite_recherche',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Unité de recherche'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='memoires_word/', verbose_name='Fichier Word'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='abstract',
            field=models.TextField(blank=True, null=True, verbose_name='Résumé'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('depot_en_ligne', 'Dépôt en ligne effectué'), ('convocation_envoyee', 'Convocation envoyée'), ('relance_envoyee', 'Relance envoyée'), ('en_attente_verification', 'En attente de vérification physique'), ('verification_ok', 'Vérification physique OK'), ('rejete', 'Rejeté'), ('en_attente_quitus', 'En attente de signature du quitus'), ('quitus_disponible', 'Quitus disponible'), ('quitus_retire', 'Quitus retiré'), ('abandonne', 'Abandonné')], default='brouillon', max_length=25, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission en ligne'),
        ),
        migrations.AlterField(
            model_name='memoire',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titre du document'),
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['matricule'], name='memoires_me_matricu_976156_idx'),
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['status'], name='memoires_me_status_9710fc_idx'),
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['author', 'status'], name='memoires_me_author__7a57e3_idx'),
        ),
    ]
