# Generated by Django 5.0.4 on 2026-08-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0003_alter_memoire_options_remove_memoire_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='archive_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Chemin du document archivé'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='memoire',
            name='document_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du document archivé'),
        ),
        migrations.AddField(
            model_name='memoire',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de séquence'),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2026, verbose_name='Année')),
                ('document_type', models.CharField(choices=[('MEMOIRE', 'Mémoire de Master'), ('THESE', 'Thèse de Doctorat')], max_length=10, verbose_name='Type de document')),
                ('faculty', models.CharField(max_length=50, verbose_name='Faculté')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Compteur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'document_type', 'faculty'],
                'unique_together': {('year', 'document_type', 'faculty')},
            },
        ),
    ]
