# Generated by Django 5.0.4 on 2026-08-04 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoires', '0004_add_archive_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memoire',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Document archivé'),
        ),
        migrations.AddIndex(
            model_name='memoire',
            index=models.Index(fields=['is_archived'], name='memoires_me_is_arch_77d9c1_idx'),
        ),
    ]
