# Generated by Django 5.0.4 on 2026-07-21 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Clé de configuration')),
                ('value', models.TextField(blank=True, verbose_name='Valeur')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description du paramètre')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du Portail',
                'verbose_name_plural': 'Configurations du Portail',
                'ordering': ['key'],
            },
        ),
    ]
